name: ci_pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: "test on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Perch/Hoplite and its dependencies via pip.
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          pip install absl-py
          pip install requests
          pip install tensorflow-cpu
          pip install git+https://github.com/google-research/hoplite.git
      - name: Test db with unittest
        run: python -m unittest discover -s hoplite/db/tests -p "*test.py"
      - name: Test taxonomy with unittest
        run: python -m unittest discover -s hoplite/taxonomy -p "*test.py"
      - name: Test zoo with unittest
        run: python -m unittest discover -s hoplite/zoo -p "*test.py"
      - name: Test agile with unittest
        run: python -m unittest discover -s hoplite/agile/tests -p "*test.py"
